package com.alexp.anydownload.data

import android.content.Context
import android.net.Uri
import android.webkit.CookieManager
import com.alexp.anydownload.CookieStatus
import java.io.File

class CookieRepository(private val context: Context) {
    private val cookiesFile = File(context.filesDir, COOKIES_FILE_NAME)
    private val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    fun getCookiesPath(): String? {
        return cookiesFile.takeIf { it.isFile && it.length() > 0 }?.absolutePath
    }

    fun getStatus(): CookieStatus {
        if (!cookiesFile.isFile || cookiesFile.length() == 0L) {
            return CookieStatus(isLoaded = false)
        }

        val parsed = parseCookies(cookiesFile.readText())
        return CookieStatus(
            isLoaded = true,
            cookieCount = parsed.cookieCount,
            domains = parsed.domains,
            importedAtMillis = prefs.getLong(KEY_IMPORTED_AT, 0L).takeIf { it > 0 },
            hasInstagram = parsed.domains.any { it.contains("instagram.com") },
            hasFacebook = parsed.domains.any { it.contains("facebook.com") || it.contains("fb.com") },
            hasTwitter = parsed.domains.any {
                it.contains("twitter.com") || it.contains("x.com")
            },
        )
    }

    fun saveFromWebViewLogin(platform: LoginPlatform): Result<CookieStatus> {
        return runCatching {
            val cookieManager = CookieManager.getInstance()
            cookieManager.flush()
            if (!platform.isLoggedIn(cookieManager)) {
                throw IllegalStateException("Login not completed. Finish signing in to ${platform.label} first.")
            }

            val newLines = WebViewCookieConverter.extractNetscapeLines(platform, cookieManager)
            if (newLines.isEmpty()) {
                throw IllegalStateException("No cookies captured for ${platform.label}.")
            }

            mergeNetscapeLines(platform, newLines)
            prefs.edit().putLong(KEY_IMPORTED_AT, System.currentTimeMillis()).apply()
            getStatus()
        }
    }

    fun importFromUri(uri: Uri): Result<CookieStatus> {
        return runCatching {
            val content = context.contentResolver.openInputStream(uri)?.use { stream ->
                stream.bufferedReader().readText()
            } ?: throw IllegalArgumentException("Could not read the selected file.")

            if (!isValidNetscapeCookies(content)) {
                throw IllegalArgumentException(
                    "Invalid cookies file. Use Connect buttons above, or export Netscape cookies.txt from a browser.",
                )
            }

            cookiesFile.writeText(content.trimEnd() + "\n")
            prefs.edit().putLong(KEY_IMPORTED_AT, System.currentTimeMillis()).apply()
            getStatus()
        }
    }

    fun clearPlatform(platform: LoginPlatform) {
        if (!cookiesFile.exists()) return

        val remaining = cookiesFile.readLines()
            .filter { line ->
                line.startsWith("#") ||
                    platform.cookieDomains.none { domain ->
                        line.startsWith(".$domain") || line.startsWith("$domain\t")
                    }
            }

        if (remaining.any { !it.startsWith("#") && it.isNotBlank() }) {
            cookiesFile.writeText(remaining.joinToString("\n").trimEnd() + "\n")
        } else {
            cookiesFile.delete()
            prefs.edit().remove(KEY_IMPORTED_AT).apply()
        }
    }

    fun clear() {
        if (cookiesFile.exists()) {
            cookiesFile.delete()
        }
        prefs.edit().remove(KEY_IMPORTED_AT).apply()
        CookieManager.getInstance().removeAllCookies(null)
    }

    private fun mergeNetscapeLines(platform: LoginPlatform, newLines: List<String>) {
        val existingLines = if (cookiesFile.exists()) {
            cookiesFile.readLines().filter { it.isNotBlank() }
        } else {
            listOf("# Netscape HTTP Cookie File", "# Generated by Any Download")
        }

        val filtered = existingLines.filter { line ->
            line.startsWith("#") ||
                platform.cookieDomains.none { domain ->
                    line.startsWith(".$domain") || line.startsWith("$domain\t")
                }
        }

        val merged = filtered + newLines
        cookiesFile.writeText(merged.joinToString("\n").trimEnd() + "\n")
    }

    private fun isValidNetscapeCookies(content: String): Boolean {
        val lines = content.lines().filter { it.isNotBlank() && !it.startsWith("#") }
        if (lines.isEmpty()) return false

        val validLines = lines.count { line ->
            val parts = line.split('\t')
            parts.size >= 7 && parts[0].isNotBlank() && parts[5].isNotBlank()
        }
        return validLines > 0
    }

    private data class ParsedCookies(
        val cookieCount: Int,
        val domains: List<String>,
    )

    private fun parseCookies(content: String): ParsedCookies {
        val domains = linkedSetOf<String>()
        var count = 0

        content.lineSequence()
            .filter { it.isNotBlank() && !it.startsWith("#") }
            .forEach { line ->
                val parts = line.split('\t')
                if (parts.size >= 7) {
                    count++
                    domains += parts[0].trim().removePrefix(".")
                }
            }

        return ParsedCookies(
            cookieCount = count,
            domains = domains.sorted(),
        )
    }

    companion object {
        private const val PREFS_NAME = "cookie_prefs"
        private const val COOKIES_FILE_NAME = "cookies.txt"
        private const val KEY_IMPORTED_AT = "imported_at"
    }
}
