package com.alexp.anydownload.data

import android.webkit.CookieManager
import java.util.concurrent.TimeUnit

object WebViewCookieConverter {
    private const val NETSCAPE_HEADER = "# Netscape HTTP Cookie File\n# Generated by Any Download\n"

    fun extractNetscapeLines(
        platform: LoginPlatform,
        cookieManager: CookieManager,
    ): List<String> {
        val expires = TimeUnit.MILLISECONDS.toSeconds(
            System.currentTimeMillis() + TimeUnit.DAYS.toMillis(365),
        )
        val lines = linkedSetOf<String>()

        for (domain in platform.cookieDomains) {
            val host = ".$domain"
            for (url in platform.cookieUrls().filter { it.contains(domain) }) {
                val header = cookieManager.getCookie(url) ?: continue
                lines += headerToNetscapeLines(host, header, expires)
            }
        }

        return lines.toList()
    }

    fun toNetscapeFile(lines: List<String>): String {
        return NETSCAPE_HEADER + lines.joinToString("\n") + "\n"
    }

    private fun headerToNetscapeLines(
        host: String,
        cookieHeader: String,
        expires: Long,
    ): List<String> {
        return cookieHeader.split(';')
            .mapNotNull { part ->
                val trimmed = part.trim()
                val separator = trimmed.indexOf('=')
                if (separator <= 0) return@mapNotNull null

                val name = trimmed.substring(0, separator).trim()
                val value = trimmed.substring(separator + 1).trim()
                if (name.isBlank()) return@mapNotNull null

                listOf(host, "TRUE", "/", "TRUE", expires.toString(), name, value).joinToString("\t")
            }
    }
}
